-- LOCAL DEV ONLY — do not run against shared/Supabase environments.

DROP TABLE IF EXISTS llm_spend_log CASCADE;
DROP TABLE IF EXISTS feedback CASCADE;
DROP TABLE IF EXISTS tool_calls CASCADE;
DROP TABLE IF EXISTS bot_turns CASCADE;
DROP TABLE IF EXISTS scheduled_jobs CASCADE;
DROP TABLE IF EXISTS out_of_bounds CASCADE;
DROP TABLE IF EXISTS observations CASCADE;
DROP TABLE IF EXISTS watch_items CASCADE;
DROP TABLE IF EXISTS themes CASCADE;
DROP TABLE IF EXISTS memories CASCADE;
DROP TABLE IF EXISTS messages CASCADE;
DROP TABLE IF EXISTS users CASCADE;
