"""Shared tool-call audit logger.

Persists every tool invocation (read or write) to mediator.tool_calls so
the agent can introspect its own past decisions. Each row carries:
  - kind: 'read' or 'write'
  - arguments + result: full payloads (jsonb)
  - summary: a short human-readable highlight for the renderer

Summaries are generated by `TOOL_SUMMARIZERS` keyed on tool_name. Tools
without a summarizer get `None`; the renderer falls back to a truncated
JSON view.
"""

from __future__ import annotations

import json
from datetime import UTC, datetime
from typing import Any, Callable

from pydantic import BaseModel

from app.services.turn_context import TurnContext


def _jsonb_payload(value: BaseModel | dict[str, Any]) -> dict[str, Any]:
    if isinstance(value, BaseModel):
        return json.loads(value.model_dump_json())
    return value


def _as_dict(value: BaseModel | dict[str, Any]) -> dict[str, Any]:
    return _jsonb_payload(value)


# ── Per-tool summarizers ────────────────────────────────────────────────
#
# Each summarizer receives (args_dict, result_dict) and returns a short
# string. Keep them well under ~200 chars; the renderer composes many
# summaries into the silent-turns hot-context block.
#
# Skip tools where args+result are already self-explanatory and short.

def _trunc(text: str | None, n: int = 80) -> str:
    if not text:
        return ""
    text = text.replace("\n", " ").strip()
    return text if len(text) <= n else text[: n - 1] + "…"


def _summary_schedule_task(args: dict[str, Any], result: dict[str, Any]) -> str | None:
    action = result.get("action")
    when = result.get("scheduled_for")
    rec = result.get("recurrence") or {}
    rec_str = ""
    if isinstance(rec, dict) and rec.get("type"):
        rec_str = f" ({rec['type']})"
    brief = _trunc(args.get("brief"), 60)
    return f"schedule_task action={action} fires={when}{rec_str} brief={brief!r}"


def _summary_schedule_checkin(args: dict[str, Any], result: dict[str, Any]) -> str | None:
    action = result.get("action")
    when = result.get("scheduled_for")
    brief = _trunc(args.get("about_what") or args.get("reason"), 60)
    return f"schedule_checkin action={action} fires={when} brief={brief!r}"


def _summary_list_scheduled_tasks(
    args: dict[str, Any], result: dict[str, Any]
) -> str | None:
    tasks = result.get("tasks") or []
    if not tasks:
        return "list_scheduled_tasks count=0"
    next_task = min(
        tasks, key=lambda t: t.get("scheduled_for") or "", default=None
    )
    brief = _trunc((next_task or {}).get("brief"), 50)
    return (
        f"list_scheduled_tasks count={len(tasks)} "
        f"next={next_task.get('scheduled_for') if next_task else None} "
        f"brief={brief!r}"
    )


def _summary_list_scheduled_checkins(
    args: dict[str, Any], result: dict[str, Any]
) -> str | None:
    checkins = result.get("checkins") or []
    return f"list_scheduled_checkins count={len(checkins)}"


def _summary_list_all_reminders(
    args: dict[str, Any], result: dict[str, Any]
) -> str | None:
    items = result.get("items") or []
    kinds = {}
    for item in items:
        k = item.get("kind", "?")
        kinds[k] = kinds.get(k, 0) + 1
    kind_summary = ", ".join(f"{v} {k}" for k, v in sorted(kinds.items()))
    return f"list_all_reminders count={len(items)} ({kind_summary})"


def _summary_send_message_part(
    args: dict[str, Any], result: dict[str, Any]
) -> str | None:
    status = result.get("status") or result.get("delivery_status")
    text = _trunc(args.get("content") or args.get("text"), 80)
    return f"send_message_part status={status} text={text!r}"


def _summary_search_messages(
    args: dict[str, Any], result: dict[str, Any]
) -> str | None:
    hits = result.get("hits") or result.get("matches") or []
    q = _trunc(args.get("query"), 40)
    return f"search_messages query={q!r} count={len(hits)}"


def _summary_recent_activity(
    args: dict[str, Any], result: dict[str, Any]
) -> str | None:
    digests = result.get("threads") or result.get("digests") or []
    return f"recent_activity threads={len(digests)}"


def _summary_set_topic_status(
    args: dict[str, Any], result: dict[str, Any]
) -> str | None:
    headline = _trunc(args.get("headline"), 80)
    return f"set_topic_status headline={headline!r}"


def _summary_get_bot_actions(
    args: dict[str, Any], result: dict[str, Any]
) -> str | None:
    actions = result.get("actions") or []
    return f"get_bot_actions count={len(actions)}"


def _summary_get_memories(args: dict[str, Any], result: dict[str, Any]) -> str | None:
    rows = result.get("memories") or result.get("rows") or []
    q = _trunc(args.get("query"), 40)
    return f"get_memories query={q!r} count={len(rows)}"


def _summary_list_watch_items(
    args: dict[str, Any], result: dict[str, Any]
) -> str | None:
    rows = result.get("items") or result.get("watch_items") or []
    return f"list_watch_items count={len(rows)}"


def _summary_check_oob(args: dict[str, Any], result: dict[str, Any]) -> str | None:
    verdict = result.get("verdict") or result.get("decision")
    return f"check_oob verdict={verdict}"


def _summary_react_to_message(
    args: dict[str, Any], result: dict[str, Any]
) -> str | None:
    emoji = args.get("emoji")
    msg_id = args.get("message_id")
    return f"react_to_message emoji={emoji!r} msg={msg_id}"


def _summary_log_feedback(args: dict[str, Any], result: dict[str, Any]) -> str | None:
    sentiment = args.get("sentiment")
    note = _trunc(args.get("content") or args.get("note"), 60)
    return f"log_feedback sentiment={sentiment} note={note!r}"


def _summary_get_tool_call(args: dict[str, Any], result: dict[str, Any]) -> str | None:
    found = bool(result.get("tool_call"))
    return f"get_tool_call id={args.get('tool_call_id')} found={found}"


def _summary_list_recent_turns(
    args: dict[str, Any], result: dict[str, Any]
) -> str | None:
    turns = result.get("turns") or []
    return f"list_recent_turns count={len(turns)}"


TOOL_SUMMARIZERS: dict[
    str, Callable[[dict[str, Any], dict[str, Any]], str | None]
] = {
    "schedule_task": _summary_schedule_task,
    "schedule_checkin": _summary_schedule_checkin,
    "list_scheduled_tasks": _summary_list_scheduled_tasks,
    "list_scheduled_checkins": _summary_list_scheduled_checkins,
    "list_all_reminders": _summary_list_all_reminders,
    "send_message_part": _summary_send_message_part,
    "search_messages": _summary_search_messages,
    "recent_activity": _summary_recent_activity,
    "set_topic_status": _summary_set_topic_status,
    "get_bot_actions": _summary_get_bot_actions,
    "get_memories": _summary_get_memories,
    "list_watch_items": _summary_list_watch_items,
    "check_oob": _summary_check_oob,
    "react_to_message": _summary_react_to_message,
    "log_feedback": _summary_log_feedback,
    "get_tool_call": _summary_get_tool_call,
    "list_recent_turns": _summary_list_recent_turns,
}


def summarize_tool_call(
    name: str, args: BaseModel | dict[str, Any], result: BaseModel | dict[str, Any]
) -> str | None:
    fn = TOOL_SUMMARIZERS.get(name)
    if fn is None:
        return None
    try:
        return fn(_as_dict(args), _as_dict(result))
    except Exception:
        # Summaries are best-effort. Never let a summarizer bug break a tool call.
        return None


async def log_tool_call(
    ctx: TurnContext,
    name: str,
    args: BaseModel | dict[str, Any],
    started_at: datetime,
    result: BaseModel | dict[str, Any],
    *,
    kind: str = "write",
) -> None:
    duration_ms = max(
        0, int((datetime.now(UTC) - started_at).total_seconds() * 1000)
    )
    summary = summarize_tool_call(name, args, result)
    await ctx.pool.execute(
        """
        INSERT INTO tool_calls
            (turn_id, tool_name, arguments, result, called_at, duration_ms,
             kind, summary)
        VALUES ($1, $2, $3::jsonb, $4::jsonb, $5, $6, $7, $8)
        """,
        ctx.turn_id,
        name,
        _jsonb_payload(args),
        _jsonb_payload(result),
        started_at,
        duration_ms,
        kind,
        summary,
    )
